class MenuItems{
  final int? id;
  final String? nombre;
  final double? precio;
  final String? imagen;
  final String? descripcion;

  const MenuItems({this.id, this.nombre, this.precio, this.imagen, this.descripcion});
}

final platos =[
  new MenuItems(id: 1, nombre: "Carne1", precio: 70, imagen: "carne.jpg", descripcion: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."),
  new MenuItems(id: 2, nombre: "Carne2", precio: 9.99, imagen: "carne1.jpg", descripcion: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like)."),
  new MenuItems(id: 3, nombre: "Carne3", precio: 39.99, imagen: "carne2.jpg", descripcion: "Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32 and 1.10.33 (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular during the Renaissance. The first line of Lorem Ipsum."),
  new MenuItems(id: 4, nombre: "Carne4", precio: 89.99, imagen: "carne.jpg", descripcion: "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined with a handful of model sentence structures, to generate Lorem Ipsum which looks reasonable. The generated Lorem Ipsum is therefore always free from repetition, injected humour, or non-characteristic words etc."),
  new MenuItems(id: 1, nombre: "Carne5", precio: 59.99, imagen: "carne1.jpg", descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis pretium iaculis. Ut volutpat porttitor rhoncus. Sed iaculis ipsum sed vehicula sodales. Vivamus pharetra fringilla libero sed rhoncus. Cras odio nunc, consectetur id semper non, scelerisque vel augue. Maecenas malesuada ante dolor, in luctus sapien ultricies egestas. Pellentesque posuere velit at arcu tempor, et congue ante congue. Donec non nisl congue, bibendum quam ac, finibus tellus. Donec ultricies velit felis, quis placerat mi gravida et. Fusce vitae enim pellentesque, gravida ante quis, varius augue. Etiam auctor faucibus purus id iaculis. Suspendisse massa massa, efficitur a orci eget, aliquet gravida metus. Morbi placerat erat nec ante tempor, tincidunt iaculis nulla laoreet."),
  new MenuItems(id: 2, nombre: "Carne6", precio: 99.99, imagen: "carne2.jpg", descripcion: "Pellentesque elementum arcu interdum risus euismod, at ornare mauris ultrices. Cras ultricies eleifend odio, ac blandit tellus mollis sed. Pellentesque ac accumsan sapien. Ut massa arcu, tristique id pretium et, pretium nec mauris. Nam mattis auctor purus et cursus. Donec eget molestie sapien, sed semper magna. Phasellus porta vel velit non tempor. Cras pulvinar tincidunt leo, vel tempus elit tincidunt sit amet. Maecenas eu eros orci. Curabitur sapien erat, pellentesque in consequat in, feugiat vehicula risus. Sed sed erat eget lacus hendrerit dictum sit amet eu purus. Integer tortor massa, pretium sed imperdiet ac, dictum sed est. Aenean in porttitor mauris. Integer ullamcorper finibus pharetra."),
  new MenuItems(id: 3, nombre: "Carne7", precio: 69.99, imagen: "carne.jpg", descripcion: "Ut sit amet elit augue. Morbi a sem vitae eros lobortis ullamcorper sit amet eu libero. Morbi sagittis, ante non porta iaculis, lorem orci blandit quam, eu porttitor elit lectus vel sem. Nulla nunc augue, mollis vitae eleifend a, iaculis nec elit. Pellentesque placerat eleifend risus vitae iaculis. Morbi ornare, arcu eget finibus maximus, velit libero faucibus metus, sit amet pulvinar diam eros ac nunc. Donec venenatis sapien tempor rutrum tempus. Nulla facilisi. Sed rutrum dictum diam, sed mollis enim suscipit vitae. Fusce tempus iaculis nisl, vitae tincidunt enim hendrerit sit amet. Ut malesuada condimentum sapien."),
  new MenuItems(id: 4, nombre: "Carne8", precio: 79.99, imagen: "carne1.jpg", descripcion: "Vivamus efficitur gravida pharetra. Aenean cursus lacinia tortor, in venenatis nibh vehicula vitae. Duis vehicula mi eget ante vestibulum faucibus. Morbi cursus in diam in volutpat. Proin vitae metus sed urna vehicula aliquet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nullam pretium nisl id velit ornare, nec porta quam porta. Nunc in ante vel lectus mollis feugiat eu sit amet purus. Morbi consequat imperdiet dolor, at sagittis dui semper a. Etiam commodo magna sagittis sapien tincidunt, vitae posuere risus sollicitudin. Morbi tincidunt odio at semper tempus. Aenean sodales neque sed purus condimentum faucibus. Donec iaculis vitae purus nec tincidunt. Proin enim ex, scelerisque eget tempor eget, volutpat vel odio. Pellentesque rutrum commodo nulla, id accumsan metus malesuada varius. Morbi eget diam mauris."),
];